spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/naver?useUnicode=true&charaterEncoding=utf-8
    username: root
    password: 1111
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    name: naver
logging:
  config: classpath:logback-dev.xml
